openapi: 3.0.0
info:
  title: Album API
  version: 1.0.0
  description: ""
paths:
  /tags:
    get:
      operationId: ""
      summary: ListTags
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTagsResponse"
        "400":
          description: Bad Request
      description: Get all tags
    parameters: []
  /tags/delete:
    post:
      operationId: ""
      summary: DeleteTags
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteTagsRequest"
  /pictures:
    get:
      operationId: ""
      summary: ListPictures
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPicturesResponse"
        "400":
          description: Bad Request
      description: List all pictures
      parameters:
        - schema:
            type: array
            items:
              type: string
          in: query
          name: tag
          description: tag
          required: true
          style: form
    parameters: []
    post:
      summary: PostPicture
      operationId: ""
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPicturesRequest"
  "/pictures/{id}":
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: GetPicture
      operationId: get-pictures-id
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPictureResponse"
        "400":
          description: Bad Request
    delete:
      summary: PutPicture
      operationId: delete-pictures-id
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
    put:
      summary: PutPicture
      operationId: put-pictures-id
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutPictureRequest"
        description: ""
components:
  schemas:
    GetTagsResponse:
      title: GetTagsResponse
      type: object
      description: ""
      properties:
        tags:
          type: array
          description: List of tags
          items:
            type: string
    DeleteTagsRequest:
      title: DeleteTagsRequest
      type: object
      properties:
        tags:
          type: array
          minItems: 1
          description: List of tags
          items:
            type: string
    PostPicturesRequest:
      title: PostPicturesRequest
      type: object
      properties:
        tags:
          type: array
          minItems: 1
          description: List of tags
          items:
            type: string
        picture:
          type: string
          description: Base64Encoded picture
        ext:
          type: string
          description: extension of file
      required:
        - tags
        - picture
        - ext
    GetPicturesResponse:
      title: GetPicturesResponse
      type: object
      properties:
        pictures:
          type: array
          description: List of pictures
          items:
            $ref: "#/components/schemas/PicturesResponseItem"
    PicturesResponseItem:
      title: PicturesResponseItem
      type: object
      properties:
        tags:
          type: array
          description: List of tags
          items:
            type: string
        fileName:
          type: string
          description: fileName
        id:
          type: string
          description: ID
    GetPictureResponse:
      title: GetPictureResponse
      type: object
      properties:
        picture:
          type: string
          description: Base64encoded picture
    PutPictureRequest:
      title: PutPictureRequest
      type: object
      properties:
        tags:
          type: array
          description: List of tags
          minItems: 1
          items:
            type: string
      required:
        - id
        - tags
  responses: {}
  securitySchemes:
    IDToken:
      name: x-authorization
      type: apiKey
      in: header
      description: CognitoIDToken
security:
  - IDToken: []
