version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "album-server"
s3_bucket = "album-server-bucket"
s3_prefix = "album-server"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
