// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

// GetPicturesResponse defines model for GetPicturesResponse.
type GetPicturesResponse struct {

	// List of pictures
	Pictures *[]PicturesResponseItem `json:"pictures,omitempty"`
}

// GetTagsResponse defines model for GetTagsResponse.
type GetTagsResponse struct {

	// List of tags
	Tags *[]string `json:"tags,omitempty"`
}

// PicturesResponseItem defines model for PicturesResponseItem.
type PicturesResponseItem struct {

	// Base64encoded picture
	Picture *string `json:"picture,omitempty"`

	// List of tags
	Tags *[]string `json:"tags,omitempty"`
}

// GetPicturesParams defines parameters for GetPictures.
type GetPicturesParams struct {

	// tag
	Tag []interface{} `json:"tag"`
}
